### PR TITLE
Fix import error of extension module "roles"

### PR DESCRIPTION
**Pull request by wdscxsj**

### CODE REVIEW

**Comment by DbxDev** [comment]
I'm not understanding this fix. Can you maybe provide a bit more context?

**Comment by wdscxsj** [comment]
Sure. To build the doc using Sphinx, `conf.py` specifies a custom extension `rule`, which is included in the `docs` directory. But the original line `sys.path.insert(0, os.path.abspath('roles'))` won't allow access to the `roles` module. That's why I changed the path to the `docs` directory, supposing `sphinx-build` is executed there.

With the proposed change, I managed to build the documentation on Windows with Python 3.7.3.

**Comment by DbxDev** [comment]
I don't understand the fix. When starting the interpreter the directory containing the script is inserted to the `sys.path` array. See [documentation](https://docs.python.org/3.7/library/sys.html#sys.path).

> As initialized upon program startup, the first item of this list, path[0], is the directory containing the script that was used to invoke the Python interpreter.

I have no issue regarding `roles`, can you maybe put the error message. Thanks.

**Comment by wdscxsj** [comment]
Sure. This is what happens when I run `sphinx-build` under the `docs` directory:

```text

WolframClientForPython-master/docs$ sphinx-build -b html . _build
Running Sphinx v2.2.0

Extension error:
Could not import extension roles (exception: No module named 'roles')
```

**Comment by DbxDev** [comment]
I can't reproduce.
I prefer using `$ python3 -msphinx` in place of `sphinx-build`, so that I know what python runtime is used.
I wrote a script to automate the build process `docs/build_docs.sh`. You may want to try it instead.

**Pull request closed without merging**
