### PR TITLE
Update path.py - MacOS - 10.14 -wolframe engine - 12_0

### PR DESCRIPTION
**Pull request by clives**
Was not working on my notebook - using the free version of wolframe engine - path invalid
while starting the session .

### CODE REVIEW

**Comment by clives** [comment]
not sure for the branch...

**Comment by riccardodivirgilio** [comment]
Thanks for the pull request, we will very likely merge this change.

**Comment by DbxDev** [comment]
Thanks for the contribution. I cherry picked your commit into a branch that will also apply the fix to Linux and Windows environments.

**Comment by DbxDev** [comment]
This was cherry picked. Closing the PR.

**Pull request closed without merging**
